<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container22dLYR7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container22dLYR7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container22dLYR7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container22dLYR7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container22dLYR7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '22dLYR7',
    'container.build_id' => '8ba4cd66',
    'container.build_time' => 1620923261,
], __DIR__.\DIRECTORY_SEPARATOR.'Container22dLYR7');
