<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerVjKVLIN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVjKVLIN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVjKVLIN.legacy');
=======
if (\class_exists(\ContainerIfUWlPJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIfUWlPJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIfUWlPJ.legacy');
>>>>>>> 55744abfa7658b3b38850710e11eec8d2c809a1d

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerVjKVLIN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVjKVLIN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VjKVLIN',
    'container.build_id' => '74e9eb6f',
    'container.build_time' => 1620943239,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVjKVLIN');
=======
    \class_alias(\ContainerIfUWlPJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIfUWlPJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IfUWlPJ',
    'container.build_id' => '7ba560aa',
    'container.build_time' => 1620994487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIfUWlPJ');
>>>>>>> 55744abfa7658b3b38850710e11eec8d2c809a1d
